% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Sat Jan  7 14:58:01 PST 1995 by kalsow  
%      modified on Thu Jul 14 13:10:18 PDT 1994 by mcjones 
%      modified on Thu Jun 17 19:14:47 PDT 1993 by harrison
%      modified on Thu May  6 21:38:22 PDT 1993 by mjordan

if equal (OS_TYPE, "POSIX")

Module("OSErrorPosix")

Interface("OSConfig")

Module("FilePosix")

implementation("FSPosix")
implementation("PipePosix")

if not equal (TARGET, "I386_DJGPP")
  implementation("PathnamePosix")
else
  % DJGPP uses Win32 Pathname to accomodate colons e.g. c:/cm3.
end

if equal (TARGET, "I386_DJGPP")
  implementation("SocketNone")
else
  implementation("SocketPosix")
end

implementation("OSConfigPosix")

module("ProcessPosixCommon")

% Cygwin can use faster spawn sometimes instead of fork/exec.
if equal (TARGET_OS, "CYGWIN")
    implementation("ProcessCygwin")
else
    implementation("ProcessPosix")
end

c_source("FilePosixC")
interface("FilePosixC")

interface("OSConfigPosixC")
c_source("OSConfigPosixC")

interface("FSPosixC")
c_source("FSPosixC")
 
end
